let events = [
  {
    key: 1,
    timelineName:"Lord Of The Rings",
    title: "La batalla de Isengard!",
    preview: "/timeLines-images/isengardBattle.jpg",
    content:"Empujados por Merry y Pippin, los Ents, seguidos por los Ucornos, invadieron el Anillo de Isengard desde el Bosque de Fangorn. Isengard era defendidos por Orcos y Hombres dirigidos por el Mago Blanco Saruman. Los atacantes rodearon Isengard, destruyeron sus puertas, derrumbaron sus muros y rompieron la presa que Saruman había construido, cuya agua inundó la Torre y los pozos que se utilizaban para crear sus máquinas de guerra.",
    link: "/events/isengardBattle",
    timeline: '1',
  },
  {
    key: 2,
    title: "La batalla del abismo de Helm!",
    preview: "/timeLines-images/helmBattle.jpg",
    content: "La Batalla del Abismo de Helm es realmente titulada Batalla de Hornburg, y tuvo lugar en la fortaleza de la montaña de Horburg, en la fortaleza llamada Abismo de Helm, en Rohan. Tuvo lugar durante la noche del 3 al 4 de marzo del 3019 (T.E.) entre los Uruk-hai enviados por Saruman y la defensa de los Rohirrim liderados por Théoden y Erkenbrand.",
    link: "/events/HelmBattle",
    timeline: '1',
  },
  {
    key: 3,
    timelineName:"World War 2",
    title: "Desembarco de Normandia",
    preview: "/timeLines-images/diaD.jpg",
    content: "hola",
    link: "/events/D_DAY",
    timeline: '2',
  },
  {
    key: 4,
    title: "Batalla de las Ardenas",
    preview: "/timeLines-images/ardenas.jpg",
    content: "",
    link: "/events/ardennesForest",
    timeline: '2',
  },
  {
    key: 5,
    timelineName:"Otoman Empire",
    title: "",
    preview: "/timeLines-images/talesme.png",
    content: "",
    link: "",
    timeline: '3',
  },
  {
    key: 6,
    title: "",
    preview: "/timeLines-images/talesme.png",
    content: "",
    link: "",
    timeline: '3',
  },
];

export default events;
